### ISSUE TITLE
First time toggling extension after reloading = extension doesnt turn on

### ISSUE THREAD

**Issue by mmattikalli** [mmattikalli/webExtension#57]
After opening your browser and the extension initially loading, toggling the switch does not do anything

To repro: Restart edge and reload extension. Turn on faceID lock and the first time you do, it should not work. The second time turning it on should work

**Comment by mmattikalli** [comment]
If you go to a webpage, then turn the extension on, it does not work

**Comment by Kaboomboom3** [comment]
Edge disables extensions by default when they are loaded locally. When loaded the content script will not run. Edge requires that the page is loaded while the extension is enabled for content scripts to run.
